"""
Output-first matching engine.

Given an optimizer result (tonnes allocated per facility), computes recovered
output quantities using DEMO-mode yield assumptions, then runs a small LP per
output type to match supply to demand nodes -- minimising transport cost
(compost only; power is assumed grid-wheeled, no haulage modelled) while
pushing to satisfy demand first via a large penalty on unmet demand.

Two output sources are modelled, explicitly labelled by scope:
  - power_mwh (PRIMARY_MAIN_NETWORK): from WTE/integrated facilities, using
    result["tonnes_allocated_tpd"] -- i.e. only what the main optimizer
    actually routed there this run. This IS part of the main network's mass
    balance and financial cost (see engine/economics.py).
  - compost_tonnes (AUXILIARY_SIDE_STREAM): from decentralised composters/
    pits' KNOWN installed capacity (NOT the separately-reported throughput
    figure -- see decentralised_compost_source._evidence in
    output_assumptions.json). This is NOT part of the main 11,862 TPD
    optimizer's mass balance or financial cost -- its own processing cost was
    never modelled, so engine/economics.py keeps its revenue/emissions
    strictly separate under auxiliary_side_streams rather than adding them
    into the main network's totals.

Missing coordinates: if a source or demand node has no coordinate, that
specific (source, demand) pair is made INELIGIBLE for matching (its LP
variable is bounded to 0), not given a silent zero transport cost -- a
zero-cost pair would make the solver artificially prefer it. A caveat records
every excluded pair.

Every yield/demand/operating-rate figure is ASSUMPTION-tagged with evidence
in output_assumptions.json. This module refuses to run outside demo mode.
"""
import json
from pathlib import Path

import numpy as np
from scipy.optimize import linprog

from .build_instance import NETWORK_FILE, haversine_km
from .model import Instance

ASSUMPTIONS_FILE = Path(__file__).resolve().parents[3] / "data_pack" / "primary_2025_26" / "output_assumptions.json"
DEMO_ASSUMPTIONS_FILE = Path(__file__).resolve().parents[3] / "data_pack" / "primary_2025_26" / "demo_assumptions.json"
UNMET_PENALTY_RS = 1e6  # Rs/unit -- large enough to always prefer matching demand over saving transport cost

STREAM_SCOPE = {
    "power_mwh": "PRIMARY_MAIN_NETWORK: generated by facility_subset WTE/integrated facilities that ARE "
                 "inside the main optimizer's mass balance and financial cost.",
    "compost_tonnes": "AUXILIARY_SIDE_STREAM: from decentralised installed capacity NOT part of the main "
                       "11,862 TPD optimizer mass balance or financial cost -- see engine/economics.py's "
                       "auxiliary_side_streams for why its revenue/emissions are kept separate.",
}


def load_output_assumptions():
    return json.load(open(ASSUMPTIONS_FILE))


def load_facility_coordinates():
    """WTE/integrated facility coordinates come from demo_assumptions.json (the same
    coordinates the main network's distance matrix uses) -- not duplicated here."""
    demo = json.load(open(DEMO_ASSUMPTIONS_FILE))
    return demo.get("coordinates", {})


def compute_output_supply(inst: Instance, result: dict, assum: dict) -> dict:
    """output_type -> list of {source_id, quantity_per_day, per_tonne_yield, evidence}"""
    if inst.mode != "demo":
        raise ValueError("output matching uses DEMO-only yield assumptions; call with a demo-mode Instance/result")
    supply = {}

    # WTE/integrated facility outputs -- only what the optimizer actually allocated this run
    for fid, tonnes in result.get("tonnes_allocated_tpd", {}).items():
        y = assum["yields"].get(fid)
        if not y or tonnes <= 0:
            continue
        qty = tonnes * y["value"]
        supply.setdefault(y["output_type"], []).append(
            {"source_id": fid, "quantity_per_day": qty, "per_tonne_yield": y["value"], "evidence": y["evidence"]}
        )

    # Decentralised compost -- from network snapshot's KNOWN installed capacity, independent
    # of the WTE allocation above (decentralised composting is not part of the main LP).
    net = json.load(open(NETWORK_FILE))
    dec = net.get("decentralised_processing", {}).get("installed_capacity_tpd", {})
    composters = dec.get("composters", {}).get("value") or 0
    pits = dec.get("compost_pits", {}).get("value") or 0
    installed_organic_input_tpd = composters + pits
    if installed_organic_input_tpd > 0:
        block = assum["decentralised_compost_source"]
        rate = block["operating_rate_assumed"]["value"]
        yld = assum["yields"]["DECENTRALISED_COMPOST"]
        qty = installed_organic_input_tpd * rate * yld["value"]
        supply.setdefault(yld["output_type"], []).append({
            "source_id": "DECENTRALISED_COMPOST",
            "quantity_per_day": qty,
            "per_tonne_yield": yld["value"],
            "evidence": (
                f"installed capacity {installed_organic_input_tpd} TPD (KNOWN, Statement 14.10) "
                f"x operating_rate {rate} (ASSUMPTION: {block['operating_rate_assumed']['evidence'][:90]}...) "
                f"x yield {yld['value']} (ASSUMPTION: {yld['evidence'][:90]}...)"
            ),
        })
    return supply


def _match_one_output_type(output_type, supplies, demand_nodes, source_coords, transport_rate):
    """LP: minimise transport cost of matched flow + UNMET_PENALTY * unmet demand.
    Variables: m[s,d] matched qty, unmet[d], unused[s]. A pair with no coordinates on
    either side is made INELIGIBLE (bounded to 0), never given a free/zero-cost route."""
    sources = [s["source_id"] for s in supplies]
    demands = [d["id"] for d in demand_nodes]
    ns, nd = len(sources), len(demands)
    caveats = []
    if ns == 0 or nd == 0:
        return {"output_type": output_type, "matches": [], "unmet_by_demand": {}, "unused_by_source": {},
                "total_supply_per_day": sum(s["quantity_per_day"] for s in supplies),
                "total_demand_per_day": sum(d["demand_quantity_per_day"]["value"] for d in demand_nodes),
                "total_matched_per_day": 0.0, "utilization_of_recovered_output_pct": 0.0,
                "demand_fulfilment_pct": 0.0, "caveats": ["no supply or no demand node for this output type"]}

    nm = ns * nd
    nv = nm + nd + ns
    m0, u0, w0 = 0, nm, nm + nd

    transport = np.zeros((ns, nd))
    ineligible = np.zeros((ns, nd), dtype=bool)
    grid_wheeled = transport_rate is None or output_type == "power_mwh"
    for i, s in enumerate(sources):
        for k, d in enumerate(demand_nodes):
            if grid_wheeled:
                transport[i, k] = 0.0  # grid-wheeled, no haulage modelled -- eligible, genuinely free
                continue
            sc, dc = source_coords.get(s), d.get("coords")
            if sc and dc:
                km = haversine_km(sc["lat"], sc["lon"], dc["lat"], dc["lon"])
                transport[i, k] = km * transport_rate
            else:
                ineligible[i, k] = True
                caveats.append(f"pair excluded (ineligible for matching): missing coordinates for "
                                f"source={s} and/or demand={d['id']} -- not modelled as free transport")

    # per-variable bounds: (0, inf) normally, (0, 0) for an ineligible pair
    lb = np.zeros(nv)
    ub = np.full(nv, np.inf)
    for i in range(ns):
        for k in range(nd):
            if ineligible[i, k]:
                ub[m0 + i * nd + k] = 0.0
    bounds = list(zip(lb, ub))

    c = np.zeros(nv)
    for i in range(ns):
        for k in range(nd):
            c[m0 + i * nd + k] = transport[i, k]
    c[u0:u0 + nd] = UNMET_PENALTY_RS

    A_eq = np.zeros((ns + nd, nv))
    b_eq = np.zeros(ns + nd)
    for i, s in enumerate(supplies):
        for k in range(nd):
            A_eq[i, m0 + i * nd + k] = 1
        A_eq[i, w0 + i] = 1
        b_eq[i] = s["quantity_per_day"]
    for k, d in enumerate(demand_nodes):
        for i in range(ns):
            A_eq[ns + k, m0 + i * nd + k] = 1
        A_eq[ns + k, u0 + k] = 1
        b_eq[ns + k] = d["demand_quantity_per_day"]["value"]

    res = linprog(c, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method="highs")
    matches = []
    for i, s in enumerate(sources):
        for k, d in enumerate(demands):
            q = res.x[m0 + i * nd + k]
            if q > 1e-6:
                matches.append({"source": s, "demand_node": d, "matched_quantity_per_day": float(q),
                                 "transport_cost_rs_per_day": float(q * transport[i, k])})
    unmet = {demands[k]: float(res.x[u0 + k]) for k in range(nd) if res.x[u0 + k] > 1e-6}
    unused = {sources[i]: float(res.x[w0 + i]) for i in range(ns) if res.x[w0 + i] > 1e-6}
    total_supply = sum(s["quantity_per_day"] for s in supplies)
    total_demand = sum(d["demand_quantity_per_day"]["value"] for d in demand_nodes)
    total_matched = sum(m["matched_quantity_per_day"] for m in matches)
    return {
        "output_type": output_type, "matches": matches, "unmet_by_demand": unmet, "unused_by_source": unused,
        "total_supply_per_day": total_supply, "total_demand_per_day": total_demand,
        "total_matched_per_day": total_matched,
        "utilization_of_recovered_output_pct": round(100 * total_matched / total_supply, 1) if total_supply else 0.0,
        "demand_fulfilment_pct": round(100 * total_matched / total_demand, 1) if total_demand else 0.0,
        "caveats": sorted(set(caveats)),
    }


def match_outputs(inst: Instance, result: dict) -> dict:
    assum = load_output_assumptions()
    supply = compute_output_supply(inst, result, assum)
    demand_by_type = {}
    for d in assum["demand_nodes"]:
        demand_by_type.setdefault(d["output_type"], []).append(d)

    source_coords = dict(load_facility_coordinates())  # WTE facilities
    source_coords["DECENTRALISED_COMPOST"] = {
        "lat": assum["decentralised_compost_source"]["source_coordinates"]["lat"],
        "lon": assum["decentralised_compost_source"]["source_coordinates"]["lon"],
    }

    out = {}
    for output_type, supplies in supply.items():
        rate = (
            None if output_type == "power_mwh"
            else assum.get("transport_cost_rs_per_tonne_km_output", {}).get("value")
        )
        matched = _match_one_output_type(
            output_type, supplies, demand_by_type.get(output_type, []), source_coords, rate
        )
        matched["stream_scope"] = STREAM_SCOPE.get(output_type, "SCOPE_NOT_DOCUMENTED")
        out[output_type] = matched
    return {
        "mode": "demo",
        "note": "All yields, operating-rate and demand figures are DEMO-mode ASSUMPTIONS -- "
                "see output_assumptions.json for evidence per value. See each output_type's "
                "stream_scope for whether it is part of the main network or an auxiliary side-stream "
                "(see engine/economics.py for how the two are kept financially/emissions-wise separate).",
        "by_output_type": out,
    }
